# Data Handling Using Python

## Array - Datastructure

#### NumPy – Introduction and Installation

- NumPy stands for ‘Numeric Python’
- Used for mathematical and scientific computations
- NumPy array is the most widely used object of the NumPy library

#### Installing related libraries
- one time activity
- can be done from terminal

**Terminal > New Terminal**

In [ ]:
pip install numpy
pip install pandas
pip install matplotlib
pip install seaborn

#### Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#### Definition - 

- NumPy arrays are multidimensional, homogeneous data structures used for efficient numerical computations in Python.  
- They are similar to Python lists but provide faster processing and require less memory.  
- Arrays can have any number of dimensions, such as 1D (vector), 2D (matrix), or higher-dimensional arrays.  
- All elements in a NumPy array must be of the same data type, ensuring performance optimization.  
- NumPy supports a wide range of data types, including integers, floats, complex numbers, and more.  
- Arrays are created using functions like `numpy.array()`, `numpy.zeros()`, `numpy.ones()`, and `numpy.arange()`.  
- NumPy arrays support vectorized operations, enabling element-wise arithmetic without explicit loops.  
- Slicing, indexing, and broadcasting enable efficient manipulation and computation on arrays.  
- NumPy integrates well with other scientific computing libraries, making it essential for data science and machine learning.  
- Arrays can be reshaped, transposed, and aggregated using built-in NumPy methods for flexible data handling.

- **Creating Arrays**
    - `np.array()` is used to create a numpy array from a list

In [3]:
arr = np.array([10, 20, 30, 40])
arr

array([10, 20, 30, 40])

In [4]:
arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr_2d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

- **Array Attributes** are the features/characteristics of an object that describes the object - 
    - **shape** - Array dimensions
    - **size** - Number of array elements
    - **dtype** - Data type of array elements
    - **ndim** - Number of array dimensions
    - **dtype.name** - Name of data type
    - **astype** - Convert an array to a different type

In [5]:
arr_2d.shape

(2, 4)

In [8]:
len(arr_2d)  # returns number of rows

2

In [9]:
arr_2d.size

8

In [6]:
arr.size

4

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr.astype(float)

array([10., 20., 30., 40.])

In [13]:
arr + 5

array([15, 25, 35, 45])

#### Array Operations

<table style="width: 80%; border-collapse: collapse; border: 1px solid #ccc; margin-left: 0; text-align: left;"> <thead> <tr style="background-color: #050A30; color: white; text-align: left;"> <th style="width: 15%; border: 1px solid #000; text-align: left;">Operation</th> <th style="width: 25%; border: 1px solid #000; text-align: left;">Syntax/Method</th> <th style="border: 1px solid #000; text-align: left;">Description</th> </tr> </thead> <tbody> <tr> <td style="border: 1px solid #000; text-align: left;">Creation</td> <td style="border: 1px solid #000; text-align: left;">numpy.array(), numpy.zeros(), numpy.ones(), numpy.arange()</td> <td style="border: 1px solid #000; text-align: left;">Create arrays from lists or generate arrays of zeros, ones, or ranges.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Indexing & Slicing</td> <td style="border: 1px solid #000; text-align: left;">arr[1], arr[1:4], arr[:,2]</td> <td style="border: 1px solid #000; text-align: left;">Access or modify elements, rows, columns, and subarrays efficiently.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Arithmetic Operations</td> <td style="border: 1px solid #000; text-align: left;">arr + 2, arr1 * arr2</td> <td style="border: 1px solid #000; text-align: left;">Vectorized element-wise addition, subtraction, multiplication, and division.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Aggregation</td> <td style="border: 1px solid #000; text-align: left;">arr.sum(), arr.mean(), arr.min(), arr.max()</td> <td style="border: 1px solid #000; text-align: left;">Compute sums, means, minima, maxima, and other aggregate statistics over arrays.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Reshaping</td> <td style="border: 1px solid #000; text-align: left;">arr.reshape(new_shape)</td> <td style="border: 1px solid #000; text-align: left;">Change the dimensions of an array without changing its data.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Stacking & Splitting</td> <td style="border: 1px solid #000; text-align: left;">numpy.vstack(), numpy.hstack(), numpy.split()</td> <td style="border: 1px solid #000; text-align: left;">Combine multiple arrays vertically or horizontally and split arrays into subarrays.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Broadcasting</td> <td style="border: 1px solid #000; text-align: left;">arr + scalar, arr1 + arr2(shape mismatch)</td> <td style="border: 1px solid #000; text-align: left;">Perform operations on arrays of different shapes by automatically expanding smaller arrays.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Sorting</td> <td style="border: 1px solid #000; text-align: left;">arr.sort(), numpy.sort(arr)</td> <td style="border: 1px solid #000; text-align: left;">Sort elements in an array in-place or return a sorted copy.</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Transposing</td> <td style="border: 1px solid #000; text-align: left;">arr.T</td> <td style="border: 1px solid #000; text-align: left;">Swap rows and columns in 2D arrays (matrices).</td> </tr> <tr> <td style="border: 1px solid #000; text-align: left;">Copying</td> <td style="border: 1px solid #000; text-align: left;">arr.copy()</td> <td style="border: 1px solid #000; text-align: left;">Create a deep copy of an array to avoid modifying the original.</td> </tr> </tbody> </table>

#### Problem Definition (CityFlow Shuttle Service, Mumbai):

CityFlow operates a shuttle service across 10 key Mumbai routes, connecting residential neighborhoods to office hubs. The goal is to analyze shuttle route performance using metrics such as daily passenger counts, satisfaction scores, and shuttle frequency. Specifically, we want to:

- Identify underperforming routes (low passenger numbers and/or low satisfaction scores)
- Decide which routes may need to be closed due to poor performance
- Highlight routes where shuttle frequency should be increased to better meet passenger demand and improve overall service quality

In [15]:
import numpy as np

# Shuttle service route names
routes = np.array(['Route A', 'Route B', 'Route C', 'Route D', 'Route E','Route F', 'Route G', 'Route H', 'Route I', 'Route J'])

# Daily passenger counts 
passenger_count = np.array([576, 432, 288, 518, 150, 720, 300, 240, 400, 265])

# Target daily passenger counts
target_passengers = np.array([500, 420, 225, 405, 200, 650, 320, 280, 450, 250])

# Shuttle frequency per route (trips per day)
shuttle_frequency = np.array([20, 15, 10, 18, 8, 25, 12, 10, 16, 9])

# Passenger satisfaction scores out of 10
satisfaction_score = np.array([8.5, 7.0, 5.8, 9.0, 4.5, 9.2, 7.5, 6.0, 8.0, 5.0])

# Profit generated from each route
profit_generated = np.array([40000, 25000, 19008, 45066, -2000, 48600, 19980, 15192, 24600, 14310])

# Target profit for each route
target_profit = np.array([30000, 22680, 14850, 35235, 6000, 43875, 21312, 17724, 27675, 13500])

###### Ex. How many shuttle routes are covered by cityflow?

In [16]:
routes.size

10

###### Ex. Which shuttle route has the highest passenger count?

In [17]:
passenger_count.max()

720

In [20]:
passenger_count.argmax() # gives index position of the largest value

5

In [23]:
routes[passenger_count.argmax()] # indexing - returns a str object

'Route F'

In [24]:
passenger_count == passenger_count.max() # returns a bool array

array([False, False, False, False, False,  True, False, False, False,
       False])

In [27]:
routes[passenger_count == passenger_count.max()] # bool-indexing/Filtering and returns an array object

array(['Route F'], dtype='<U7')

In [28]:
value = routes[passenger_count == passenger_count.max()]
value[0] # further indexing/iteration to extract individual value

'Route F'

In [29]:
routes[0] # first

'Route A'

In [30]:
routes[-1] # last

'Route J'

In [31]:
routes[0:3] # slicing

array(['Route A', 'Route B', 'Route C'], dtype='<U7')

In [32]:
routes[-3 :] # last 3 - slicing

array(['Route H', 'Route I', 'Route J'], dtype='<U7')

In [34]:
routes[[5, 2, 7]] # slicing with index positions

array(['Route F', 'Route C', 'Route H'], dtype='<U7')

###### Ex. Identify routes with passenger satisfaction scores below 6.0.

In [36]:
routes[satisfaction_score < 6.0]

array(['Route C', 'Route E', 'Route J'], dtype='<U7')

###### Ex. Which routes are not meeting their target passenger counts?

In [39]:
routes[passenger_count < target_passengers]

array(['Route E', 'Route G', 'Route H', 'Route I'], dtype='<U7')

###### Ex. Should any routes be considered for closure due to low passengers and low satisfaction? If yes, which ones?

-  low passengers - passengers < 300
-  low satisfaction - score < 6.0

In [69]:
if np.any((passenger_count<300) & (satisfaction_score<6.0)) :
    print(f"Yes - {routes[(passenger_count<300) & (satisfaction_score<6.0)]}")
else:
    print("No routes to be considered")

Yes - ['Route C' 'Route E' 'Route J']


In [53]:
lst = []
if lst :
    print("yes")
else:
    print("empty")

empty


In [56]:
result = routes[(passenger_count<10) & (satisfaction_score<6.0)]
result

array([], dtype='<U7')

In [60]:
arr = np.array([0, 1, 2, 3])
np.all(arr)  # All values in array must be True

False

In [61]:
np.any(arr)  # Any one value in the array must be True

True

###### Ex. List routes that are meeting or exceeding their passenger count targets.

###### Ex. Which routes might benefit from increasing shuttle frequency to meet demand?

HINT - 
1. Calculate passengers per trip for each route
2. Calculate average passengers per trip across all routes
3. Identify routes where passengers per trip exceed average, indicating a potential need to increase frequency

###### Ex. Find the routes where target profit is not achieved and print the percentage target achievement in sorted order

<hr><hr>

## Dataframe - Datastructure
- Pandas is an open source library in python which is know for its rich applications and utilities for all kinds of mathematical, financial and statistical functions
- It is useful in data manipulation and analysis
- It provides fast, flexible, and expressive data structures designed to make working with structured (tabular, multidimensional, potentially heterogeneous) and time series data



### Creating Dataframes

In [ ]:
employees = {"Name" : ["Jack", "Bill", "Lizie", "Jane", "George"],
            "Designation" : ["HR", "Manager", "Developer", "Intern", "Manager"],
            "Salary": [40000, 60000, 25000, 12000, 70000]}

df = pd.DataFrame(employees)
df

### Accessing Dataframes

###### Ex. Extract Name column

### Setting and Re-setting index labels

#### `df.set_index(keys, drop=True, inplace=False,)`
- Set the DataFrame index (row labels) using one or more existing columns or arrays (of the correct length). The index can replace the existing index or expand on it.
#### `df.reset_index(level=None, drop=False, inplace=False,)` 
- Reset the index of the DataFrame, and use the default one instead. If the DataFrame has a MultiIndex, this method can remove one or more levels.

### Indexing and Slicing on DataFrames
1. Based on labels - loc
2. Based on index positions - iloc

###### Ex. Extract data for "Jack"

###### Ex. Extract data for Jack and Lizie

###### Ex. Extract salary data for Jack and Lizie

###### Ex. Extract data for row index 2

###### Ex. Extract data for row index 1 to 3

### Filtering Dataframes

###### Ex. Extract salary > 50000

###### Ex. Extract salary between 20000 to 50000

###### Ex. Extract designation either as HR or Developer

###### Ex. Extract employees who name starts with J

###### Ex. Modify the salary of all employees to 80000 whose original salary is > 300000

### Operations on dataframes

###### Ex. Average Salary

###### Ex. Average Salary of managers

### Concataneting and Merging Dataframes

In [ ]:
df_jan = pd.DataFrame({"Order ID" : range(101, 104), "Sales" : np.random.randint(10000, 50000, 3)})
df_feb = pd.DataFrame({"Order ID" : range(111, 114), "Sales" : np.random.randint(10000, 50000, 3)})
df_mar = pd.DataFrame({"Order ID" : range(121, 124), "Sales" : np.random.randint(10000, 50000, 3)})

#### Concatenate
pd.concat(`tuple of dfs`, `ignore_index = False`, `axis=0`)

#### Merging Dataframes

`df1.merge(df2, how="", on = "", left_on="", right_on="", left_index= "" , right_index="")`

In [ ]:
df_emp = pd.DataFrame({"Name" : ["Jack", "Bill", "Lizie", "Jane", "George"],
            "Designation" : ["HR", "Manager", "Developer", "Intern", "Manager"]})
df_emp

In [ ]:
base_salaries = pd.DataFrame({"Designation" : ["HR", "Developer", "Manager", "Senior Manager"],
            "Salary": [40000, 25000, 70000, 1000000]})
base_salaries

#### Inner Merge

In [ ]:
df_emp.merge(base_salaries, how="inner", on = "Designation")  # returns only common rows

#### Left Merge

In [ ]:
df_emp.merge(base_salaries, how="left", on = "Designation")  # returns all rows from left table

#### Right Merge

In [ ]:
df_emp.merge(base_salaries, how="right", on = "Designation")  # returns all rows from right table

#### Outer Merge

In [ ]:
df_emp.merge(base_salaries, how="outer", on = "Designation")  # returns all rows from both tables

<hr><hr>

## Data Manipulation using `pandas`

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams["figure.figsize"] = (6, 2)
# Title
plt.rcParams['axes.titlesize'] = "medium"        # Title font size
plt.rcParams['axes.titlecolor'] = 'midnightblue' # Title font color

# X and Y axis labels
plt.rcParams['axes.labelsize'] = "x-small"          # Label font size
plt.rcParams['axes.labelcolor'] = 'darkslategrey' # Label font color

# Tick labels
plt.rcParams['xtick.color'] = 'darkslategrey'        # X-axis tick color
plt.rcParams['ytick.color'] = 'darkslategrey'        # Y-axis tick color
plt.rcParams['xtick.labelsize'] = "x-small"          # X-axis tick size
plt.rcParams['ytick.labelsize'] = "x-small"          # Y-axis tick size

# Legend
plt.rcParams['legend.fontsize'] = "x-small"          # Legend text size
plt.rcParams['legend.edgecolor'] = 'black'   # Legend border color
plt.rcParams['legend.facecolor'] = 'lightgray' # Legend background color
plt.rcParams['legend.labelcolor'] = 'darkslategrey'  # Legend label text color

###### Ex. Read data from coffee_sales.csv

#### Check for null values
`df.isna()` - Detect missing values. Return a boolean same-sized object indicating if the values are NA.

#### Remove/Replace nulls

- `df.fillna(value=None, inplace=False)` - Fill NA/NaN values using the specified method.
- `df.dropna(axis = 0, how = "any", inplace = False)`
    - axis 0 for row or 1 for column
    - how - {any or all}

##### Note - 
This is older syntax. New syntax to be followed is - `df.method({col: value}, inplace=True)`

#### Data Cleaning

###### Ex. Convert all numeric column to float

#### Add Column by calculation to the dataframe

###### Ex. Check the status of target sales and add it to the dataframe as a new column

###### Ex. Countplot

#### Working with date column

###### Ex. Convert date column to date type

###### Ex. Trend and Sesonality

#### Sorting Dafatrame
- df.sort_values(`ascending=True`, `inplace=False`, `na_position = {"first","last"}`)
- df.sort_index(`ascending=True`, `inplace=False`)

#### Aggregating Dataframes
- `df.groupby(by=None,as_index=True, sort=True)`

###### Ex. Bar and pie chart

#### Correlation

###### Ex. Heatmap - correlation - housing prices example